# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    container:
      image: ${{ github.actor }}/docker.datascience:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Clonen repository
        run: git clone https://github.com/hsteinshiromoto/covid19_nsw.git

      # Runs a single command using the runners shell
      - name: Create html file
        run: bash bin/blog_publish.sh Bayesian_exponential_model 
        
      - uses: actions/upload-artifact@v2
        with:
          name: Make Artifact
          path: notebooks/Bayesian_exponential_model.html
          if-no-files-found: error
          retention-days: 7
