# This is a basic workflow to help you get started with Actions

name: Publish Notebook

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - feature/**
      - release/**
    # Publish `v1.2.3` tags as releases.
    tags:        
      - '**'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  get_container:
    runs-on: ubuntu-latest

    container:
        image: ghcr.io/${{ github.actor }}/covid19_nsw/covid19_nsw
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Publish
        run: cd /home/vscode/covid19_nsw && bash bin/blog_publish.sh Bayesian_exponential_model

      - uses: actions/upload-artifact@v2
        with:
          name: Bayesian exponential model
          path: /home/vscode/covid19_nsw/notebooks/Bayesian_exponential_model.html
          if-no-files-found: error
          retention-days: 14