# This is a basic workflow to help you get started with Actions

name: Publish Notebook

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - feature/**
      - release/**
      - main
    # Publish `v1.2.3` tags as releases.
    tags:        
      - '**'
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  publish_notebook:
    runs-on: ubuntu-latest

    container:
        image: ghcr.io/${{ github.actor }}/covid19_nsw/covid19_nsw
        options: --user root # N.B. Necessary to run actions/checkout@v2
        credentials:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # N.B. Necessary to reinstall Jupyter
      - name: Install Jupyter
        run: pip install jupyter

      - name: Convert Notebooks
        run: jupyter nbconvert --to html notebooks/Bayesian_exponential_model.ipynb

      - name: Add Jekyll Header
        run: bash bin/blog_publish.sh Bayesian_exponential_model 2021-08-04-blog-post_predicting_nsw_covid_cases

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bayesian exponential model
          path: notebooks/2021-08-04-blog-post_predicting_nsw_covid_cases.html
          if-no-files-found: error
          retention-days: 14
          workflow_conclusion: success

      - name: Pushes test file
        uses: dmnemec/copy_file_to_another_repo_action@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source_file: 'notebooks/2021-08-04-blog-post_predicting_nsw_covid_cases.html'
          destination_repo: 'hsteinshiromoto/hsteinshiromoto.github.io'
          destination_folder: '_posts'
          user_email: 'h.stein.shiromoto@gmail.com'
          user_name: 'hsteinshiromoto'
          commit_message: 'Publish notebook html'
          destination_branch: 'master'